[package]
name = "rpm-writer"
version = "0.1.0"
authors = ["Demi Marie Obenour <demi@invisiblethingslab.com>"]
edition = "2018"

[dependencies]
rpm-parser = { version = "0.1.0", path = "../rpm-parser" }
rpm-crypto = { version = "0.1.0", path = "../rpm-crypto", optional = true }
openpgp-parser = { version = "0.1.0", path = "../openpgp-parser", optional = true }

[features]
bin = ["openpgp-parser", "rpm-crypto"]

[[bin]]
name = "rpmcanon"
path = "bin/rpmcanon.rs"
required-features = ["bin"]
