[package]
name = "rpm-crypto"
version = "0.1.0"
authors = ["Demi Marie Obenour <demi@invisiblethingslab.com>"]
edition = "2018"

[dependencies]
openpgp-parser = { version = "0.1.0", path = "../openpgp-parser" }
