[package]
name = "rpm-crypto"
version = "0.2.1"
authors = ["Demi Marie Obenour <demi@invisiblethingslab.com>"]
# edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
openpgp-parser = { version = "0.2.1", path = "../openpgp-parser" }
